# Generated by Django 5.1.5 on 2025-02-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qprint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printingshop',
            name='shop_owner',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='shop_owner',
        ),
        migrations.DeleteModel(
            name='ShopOwner',
        ),
    ]
