# Generated by Django 5.1.4 on 2025-02-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qprint', '0002_remove_printingshop_shop_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='additional_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='time_limit',
            field=models.CharField(choices=[('5min', '5 Minutes'), ('10min', '10 Minutes'), ('15min', '15 Minutes')], default='5min', max_length=5),
        ),
    ]
